"""El código del curso lo genera la base, y no se rompe cuando el identificador crece (D32).

**Este archivo es la única red real de la expresión de `curso.codigo`.**
`test_la_migracion_escrita_a_mano_cuadra_con_los_modelos` corre `alembic check`, y esa
comparación **ignora las columnas generadas**: si el `Computed(...)` del modelo y el
`GENERATED ALWAYS AS ... STORED` de la migración se desincronizan, `alembic check` sigue en
verde y nadie se entera hasta que un curso con identificador de cuatro dígitos falla su alta.

Por eso el test central siembra la secuencia con `setval` y comprueba los identificadores
999, 1000 y 1001: son los tres que están del lado de la frontera donde `lpad` trunca. Y el
control negativo levanta la expresión **sin** `greatest` para demostrar que el test central no
pasa por el motivo equivocado.

**Y la secuencia hay que restaurarla.** En PostgreSQL **las secuencias no son
transaccionales**: un `setval` sobrevive al `rollback()` del fixture `db_session` y ensucia
los tests que corran después, según el orden de ejecución — un fallo que aparece en otro
archivo y parece no tener relación. Se leen `last_value` **e** `is_called` antes de tocar
nada, porque restaurar con `is_called = true` sobre una secuencia que nunca se usó deja el
contador corrido en uno.
"""

from __future__ import annotations

import pytest
from sqlalchemy import text
from sqlalchemy.exc import DBAPIError
from sqlalchemy.orm import Session

from app.tests.factories import crear_curso

#: Tabla auxiliar del control negativo, con la expresión **sin** `greatest`: la que la
#: migración tenía al principio y que hace fallar el alta del curso 1000 por una colisión de
#: código en vez de dejarlo crearse.
TABLA_CONTROL = "prueba_codigo_truncado"


def test_el_codigo_tiene_la_forma_de_cur_mas_tres_digitos(db_session: Session) -> None:
    curso = crear_curso(db_session, nombre="Python Inicial")
    db_session.refresh(curso)

    assert curso.codigo == f"CUR{curso.id:03d}", (
        "el código tiene que salir del identificador de la fila con al menos tres dígitos"
    )


def test_el_codigo_no_se_puede_escribir_en_el_insert(db_session: Session) -> None:
    """`GENERATED ALWAYS` y no `BY DEFAULT`: nadie puede informar un código.

    Es lo que distingue "el sistema lo genera" de "el sistema lo propone y acepta que lo
    pisen": con `BY DEFAULT`, un `INSERT` con `codigo` lo sobreescribe en silencio.
    """
    with pytest.raises(DBAPIError) as error:
        db_session.execute(
            text("INSERT INTO curso (nombre, nombre_norm, codigo) "
                 "VALUES ('Impostor', 'IMPOSTOR', 'CUR999')")
        )

    assert "generated" in str(error.value).lower(), (
        "la base tiene que rechazar el INSERT que informa el código. Error: "
        f"{error.value}"
    )


def test_el_codigo_no_trunca_mas_alla_de_tres_digitos(db_session: Session) -> None:
    """El `greatest` de la expresión, verificado en la frontera donde `lpad` trunca.

    Sin `greatest`, `lpad(id::text, 3, '0')` devuelve `'100'` para el identificador 1000, que
    ya es del identificador 100: el alta del curso 1000 falla por una colisión de código en
    vez de crearse, con un error que no señala la causa.
    """
    anterior = db_session.execute(text("SELECT last_value, is_called FROM curso_id_seq")).one()

    try:
        # El `false` es lo que hace que el **próximo** `nextval` devuelva 999.
        db_session.execute(text("SELECT setval('curso_id_seq', 999, false)"))

        codigos = []
        for numero in (999, 1000, 1001):
            curso = crear_curso(db_session, nombre=f"Curso {numero}")
            db_session.refresh(curso)
            codigos.append(curso.codigo)

        assert codigos == ["CUR999", "CUR1000", "CUR1001"]
        assert len(set(codigos)) == 3, "los tres códigos tienen que ser distintos"
    finally:
        db_session.execute(
            text("SELECT setval('curso_id_seq', :last_value, :is_called)"),
            {"last_value": anterior.last_value, "is_called": anterior.is_called},
        )


def test_sin_greatest_el_codigo_se_repite_y_choca(db_session: Session) -> None:
    """Control negativo: comprueba que el test anterior no pasa por el motivo equivocado.

    Si alguien "corrige" la expresión de `curso.codigo` volviendo a esta, el test central se
    pone rojo con el motivo real, y este explica por qué.
    """
    db_session.execute(text(f"DROP TABLE IF EXISTS {TABLA_CONTROL}"))
    db_session.execute(
        text(
            f"""
            CREATE TABLE {TABLA_CONTROL} (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                codigo varchar(50)
                    GENERATED ALWAYS AS ('CUR' || lpad(id::text, 3, '0')) STORED,
                CONSTRAINT uq_control UNIQUE (codigo)
            )
            """
        )
    )
    db_session.execute(text(f"SELECT setval('{TABLA_CONTROL}_id_seq', 100, false)"))
    db_session.execute(text(f"INSERT INTO {TABLA_CONTROL} DEFAULT VALUES"))
    db_session.execute(text(f"SELECT setval('{TABLA_CONTROL}_id_seq', 1000, false)"))

    with pytest.raises(DBAPIError) as error:
        db_session.execute(text(f"INSERT INTO {TABLA_CONTROL} DEFAULT VALUES"))

    detalle = str(error.value)
    assert "uq_control" in detalle, f"la colisión tiene que venir del índice único: {detalle}"
    assert "CUR100" in detalle, (
        f"el identificador 1000 tiene que truncar al mismo código que el 100: {detalle}"
    )
